### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by valentina-s** [orcasound/orca-action-workflow#31]
@Molkree 
Add a license to your repo. Feel free to [select any open source license](https://choosealicense.com/). Some popular options are MIT/BSD licenses (very open), Apache (requires users to explain modifications), you can check options with attribution/without attribution. GPL licenses are more restricted. We can discuss it if you have any questions.

**Comment by Molkree** [comment]
Well, I would like as open as possible I guess (The Unlicense?) but it might be just being me naive?
Out of 21 Orcasound repositories, I see 4 AGPL-3.0, 1 Apache-2.0, 9 MIT, 1 CC0-1.0 and 6 don't have a license.
I'll probably go with MIT then.
